// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System.Collections.Generic;
using Newtonsoft.Json;
using PropertyChanged;

namespace ImgurPortable.Entities
{
    [ImplementPropertyChanged]
    public class AccountStats
    {
        [JsonProperty("total_images")]
        public int TotalImages { get; set; }

        [JsonProperty("total_albums")]
        public int TotalAlbums { get; set; }

        [JsonProperty("disk_used")]
        public string DiskUsed { get; set; }

        [JsonProperty("bandwidth_used")]
        public string BandwidthUsed { get; set; }

        [JsonProperty("top_images")]
        public object[] TopImages { get; set; }

        [JsonProperty("top_albums")]
        public object[] TopAlbums { get; set; }

        [JsonProperty("top_gallery_comments")]
        public TopGalleryCommentCollection TopGalleryComments { get; set; }
    }
}
