// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace ImgurPortable.Entities
{

    public class TopGalleryComment
    {
        [JsonProperty("id")]
        public int Id { get; set; }

        [JsonProperty("image_id")]
        public string ImageId { get; set; }

        [JsonProperty("comment")]
        public string Comment { get; set; }

        [JsonProperty("author")]
        public string Author { get; set; }

        [JsonProperty("author_id")]
        public int AuthorId { get; set; }

        [JsonProperty("on_album")]
        public bool OnAlbum { get; set; }

        [JsonProperty("album_cover")]
        public object AlbumCover { get; set; }

        [JsonProperty("ups")]
        public int Ups { get; set; }

        [JsonProperty("downs")]
        public int Downs { get; set; }

        [JsonProperty("points")]
        public int Points { get; set; }

        [JsonProperty("datetime")]
        public int Datetime { get; set; }

        [JsonProperty("parent_id")]
        public int ParentId { get; set; }

        [JsonProperty("deleted")]
        public bool Deleted { get; set; }

        [JsonProperty("vote")]
        public object Vote { get; set; }
    }

    public class Data
    {

        [JsonProperty("total_images")]
        public int TotalImages { get; set; }

        [JsonProperty("total_albums")]
        public int TotalAlbums { get; set; }

        [JsonProperty("disk_used")]
        public string DiskUsed { get; set; }

        [JsonProperty("bandwidth_used")]
        public string BandwidthUsed { get; set; }

        [JsonProperty("top_images")]
        public object[] TopImages { get; set; }

        [JsonProperty("top_albums")]
        public object[] TopAlbums { get; set; }

        [JsonProperty("top_gallery_comments")]
        public TopGalleryComment[] TopGalleryComments { get; set; }
    }

    public class AccountStats
    {

        [JsonProperty("data")]
        public Data Data { get; set; }

        [JsonProperty("success")]
        public bool Success { get; set; }

        [JsonProperty("status")]
        public int Status { get; set; }
    }

}
