// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using PropertyChanged;

namespace ImgurPortable.Entities
{
    [ImplementPropertyChanged]
    public class GalleryProfile
    {

        [JsonProperty("total_gallery_comments")]
        public int TotalGalleryComments { get; set; }

        [JsonProperty("total_gallery_likes")]
        public int TotalGalleryLikes { get; set; }

        [JsonProperty("total_gallery_submissions")]
        public int TotalGallerySubmissions { get; set; }

        [JsonProperty("trophies")]
        public TrophyCollection Trophies { get; set; }
    }

}
